# Generated by Django 4.2.7 on 2023-11-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
